Repository pesto-students/batch-11-fluxo, pull requests merged in 2019-12, with the labels that each got.

#36 feat: Complete Flux workflow
  package.json
  server/package.json
  server/src/app.js
  server/src/app/README.md
  server/src/app/__tests__/routes/flux.test.js
  server/src/app/__tests__/userRegister.test.js
  server/src/app/controllers/fluxController.js
  server/src/app/controllers/integratedAppController.js
  server/src/app/controllers/userLogin.js
  server/src/app/controllers/userRegister.js
  server/src/app/middlewares/auth.js
  server/src/app/models/Flux.js
  server/src/app/models/IntegratedApps.js
  server/src/app/routes/fluxRouter.js
  server/src/app/routes/index.js
  server/src/app/routes/integRouter.js
  server/src/app/routes/integratedAppRouter.js
  server/src/app/service/fluxService.js
  server/src/app/service/integratedAppService.js
  server/src/app/service/integrationService.js
  server/src/index.js
  server/src/logger/index.js
  server/src/thirdparty/__tests__/util/inMemoryDb.js
  server/src/thirdparty/config.js
  server/src/thirdparty/routes/index.js
  server/src/thirdparty/slackAPI/service.js
  yarn.lock
Labels: feature

#30 feat: Complete the Login page UI
  client/src/Component/LandingPage/LandingHeader/LandingHeader.js
  client/src/Component/Onboarding/Login/Login.js
  client/src/Component/Onboarding/Login/Login.module.scss
  client/src/Component/Onboarding/Login/loginFormConfig.js
  client/src/Component/Onboarding/SignUp/SignUp.js
  client/src/Component/Onboarding/SignUp/SignUp.module.scss
  client/src/Component/Onboarding/SignUp/formElementConfig.js
  client/src/Component/Onboarding/formValidation.js
  client/src/Container/App/App.js
  client/src/MaterialUI/Component/Error/Error.module.scss
  client/src/apis/onBoarding/onBoarding.js
  client/src/constants/constants.js
Labels: feature

#35 feat: Complete UI for creating flux and connecting apps
  client/package.json
  client/src/Component/CreateFlux/CreateFlux.js
  client/src/Component/CreateFlux/CreateFluxBody/ActionSection/Action.module.scss
  client/src/Component/CreateFlux/CreateFluxBody/ActionSection/ActionSection.js
  client/src/Component/CreateFlux/CreateFluxBody/CreateFluxBody.js
  client/src/Component/CreateFlux/CreateFluxBody/CreateFluxBody.module.scss
  client/src/Component/CreateFlux/CreateFluxBody/EventSection/Event.module.scss
  client/src/Component/CreateFlux/CreateFluxBody/EventSection/EventSection.js
  client/src/Component/CreateFlux/CreateFluxHeader/CreateFluxHeader.js
  client/src/Component/LandingPage/LandingHeader/LandingHeader.js
  client/src/Container/App/App.js
  client/src/MaterialUI/Component/Button/Button.js
  client/src/MaterialUI/Component/Menu/Menu.js
  client/src/MaterialUI/Component/SimpleSelect/SimpleSelect.js
  client/src/MaterialUI/Component/TopBar/TopBar.js
  client/src/MaterialUI/Import/Import.js
  client/src/constants/constants.js
  yarn.lock
Labels: feature

#39 feat: Dashboard UI for created fluxes
  client/src/Component/CreateFlux/CreateFlux.js
  client/src/Component/Dashboard/Dashboard.js
  client/src/Component/Dashboard/Dashboard.module.scss
  client/src/Component/Dashboard/DeleteFluxModal/DeleteFluxModal.js
  client/src/Component/Dashboard/DeleteFluxModal/DeleteFluxModal.module.scss
  client/src/Component/Dashboard/dashboardConfig.js
  client/src/Component/Header/Header.js
  client/src/Container/App/App.js
  client/src/MaterialUI/Component/Card/Card.js
  client/src/MaterialUI/Component/Card/Card.module.scss
  client/src/MaterialUI/Component/Modal/Modal.js
  client/src/MaterialUI/Component/SnackBar/SnackBar.js
  client/src/MaterialUI/Component/Toggle/Toggle.js
  yarn.lock
Labels: feature

#55 feat: Add integrate app button component
  client/src/Component/IntegrateButton/IntegrateButton.js
  client/src/Component/README.md
  client/src/apis/apps/index.js
  server/package.json
  server/src/app.js
  server/src/thirdparty/slackAPI/controller.js
  server/views/authStatus.ejs
  yarn.lock
Labels: feature

#63 enhancement: Add user detail and logout api
  server/src/app/controllers/userLogin.js
  server/src/app/controllers/userLogout.js
  server/src/app/routes/users.js
Labels: enhancement

#65 fix: Allow PUT,DELETE requests for cors,
  Procfile
  server/src/app.js
Labels: bug

#66 feat: Add flux history
  server/src/app/controllers/fluxController.js
  server/src/app/models/FluxHistory.js
  server/src/app/routes/fluxRouter.js
  server/src/app/service/fluxService.js
  server/src/app/service/integrationService.js
  yarn.lock
Labels: feature

#86 Fix: Add same account to multiple users
  .gitignore
  server/src/thirdparty/__tests__/services/slack.test.js
  server/src/thirdparty/slackAPI/service.js
Labels: bug
